function show_gui_options(callerHandle, populateWithDefaultAndNoGUI)
% show_gui_options(callerHandle, populateWithDefaultAndNoGUI)
% second argument is used when the function is not used as a callback but 
% in the start of the toolbox GUI in order to populate measure_projection.option field
% with default values.


% get STUDY from the base workspace
STUDY = evalin('base', 'STUDY;');

if isfield(STUDY, 'measureProjection') && isfield(STUDY.measureProjection, 'option') && isfield(STUDY.measureProjection.option, 'properties') && ~isempty(STUDY.measureProjection.option.properties)
    properties = STUDY.measureProjection.option.properties;
else

properties = [ ...

    % indivisual measure categorizes
    PropertyGridField('erpSignificance', double(0.01), ...
        'Type', PropertyType('denserealdouble', 'scalar', [0 1]), ...
        'Category', 'ERP', ...
        'DisplayName', 'Significance', ...
        'Description', 'Significance threshold (p value) for selecting brain locations with high measure convergence.') ...
        
        PropertyGridField('erspSignificance', double(0.01), ...
        'Type', PropertyType('denserealdouble', 'scalar', [0 1]), ...
        'Category', 'ERSP', ...
        'DisplayName', 'Significance', ...
        'Description', 'Significance threshold (p value) for selecting brain locations with high measure convergence.') ...
        
        PropertyGridField('itcSignificance', double(0.01), ...
        'Type', PropertyType('denserealdouble', 'scalar', [0 1]), ...
        'Category', 'ITC', ...
        'DisplayName', 'Significance', ...
        'Description', 'Significance threshold (p value) for selecting brain locations with high measure convergence.') ...
        
        PropertyGridField('specSignificance', double(0.01), ...
        'Type', PropertyType('denserealdouble', 'scalar', [0 1]), ...
        'Category', 'Spec', ...
        'DisplayName', 'Significance', ...
        'Description', 'Significance threshold (p value) for selecting brain locations with high measure convergence.') ...
        
        PropertyGridField('siftSignificance', double(0.01), ...
        'Type', PropertyType('denserealdouble', 'scalar', [0 1]), ...
        'Category', 'SIFT', ...
        'DisplayName', 'Significance', ...
        'Description', 'Significance threshold (p value) for selecting brain locations with high measure convergence.') ...
        
        % domain correlation
         PropertyGridField('erpMaxCorrelation', double(0.7), ...
        'Type', PropertyType('denserealdouble', 'scalar', [-1 1]), ...
        'Category', 'ERP', ...
        'DisplayName', 'Max Domain Exemplar Correlation', ...
        'Description', 'Maximum correlation allowed between Domain exemplars. Higher correlation values result in creation of more Domains.') ...
        
        PropertyGridField('erspMaxCorrelation', double(0.8), ...
        'Type', PropertyType('denserealdouble', 'scalar', [-1 1]), ...
        'Category', 'ERSP', ...
        'DisplayName', 'Max Domain Exemplar Correlation', ...
        'Description', 'Maximum correlation allowed between Domain exemplars. Higher correlation values result in creation of more Domains.') ...
        
        PropertyGridField('itcMaxCorrelation', double(0.8), ...
        'Type', PropertyType('denserealdouble', 'scalar', [-1 1]), ...
        'Category', 'ITC', ...
        'DisplayName', 'Max Domain Exemplar Correlation', ...
        'Description', 'Maximum correlation allowed between Domain exemplars. Higher correlation values result in creation of more Domains.') ...
        
        PropertyGridField('specMaxCorrelation', double(0.9), ...
        'Type', PropertyType('denserealdouble', 'scalar', [-1 1]), ...
        'Category', 'Spec', ...
        'DisplayName', 'Max Domain Exemplar Correlation', ...
        'Description', 'Maximum correlation allowed between Domain exemplars. Higher correlation values result in creation of more Domains.') ...
        
        PropertyGridField('siftMaxCorrelation', double(0.8), ...
        'Type', PropertyType('denserealdouble', 'scalar', [-1 1]), ...
        'Category', 'SIFT', ...
        'DisplayName', 'Max Domain Exemplar Correlation', ...
        'Description', 'Maximum correlation allowed between Domain exemplars. Higher correlation values result in creation of more Domains.') ...
        
        % FDR
        PropertyGridField('erpFdrCorrection', false, ...
        'Category', 'ERP', ...
        'DisplayName', 'FDR Correction', ...
        'Description', 'Correct significane threshold for multiple comparisons using FDR method. Reference: Benjamini, Y. & Hochberg, Y. (1995) Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society, Series B (Methodological). 57(1), 289-300.') ...
        
        PropertyGridField('erspFdrCorrection', false, ...
        'Category', 'ERSP', ...
        'DisplayName', 'FDR Correction', ...
        'Description', 'Correct significane threshold for multiple comparisons using FDR method. Reference: Benjamini, Y. & Hochberg, Y. (1995) Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society, Series B (Methodological). 57(1), 289-300.') ...
        
        PropertyGridField('itcFdrCorrection', false, ...
        'Category', 'ITC', ...
        'DisplayName', 'FDR Correction', ...
        'Description', 'Correct significane threshold for multiple comparisons using FDR method. Reference: Benjamini, Y. & Hochberg, Y. (1995) Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society, Series B (Methodological). 57(1), 289-300.') ...
        
        PropertyGridField('specFdrCorrection', false, ...
        'Category', 'Spec', ...
        'DisplayName', 'FDR Correction', ...
        'Description', 'Correct significane threshold for multiple comparisons using FDR method. Reference: Benjamini, Y. & Hochberg, Y. (1995) Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society, Series B (Methodological). 57(1), 289-300.') ...
        
        PropertyGridField('siftFdrCorrection', false, ...
        'Category', 'SIFT', ...
        'DisplayName', 'FDR Correction', ...
        'Description', 'Correct significane threshold for multiple comparisons using FDR method. Reference: Benjamini, Y. & Hochberg, Y. (1995) Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society, Series B (Methodological). 57(1), 289-300.') ...
        
        % All measures category.
         PropertyGridField('standardDeviationOfEstimatedDipoleLocation', double(12), ...
        'Type', PropertyType('denserealdouble', 'scalar', [1 50]), ...
        'Category', 'Projection', ...
        'DisplayName', 'Std. of Dipole Density', ...
        'Description', 'Standard Deviation (in mm) of truncated Gaussian) density function which represents each dipole.') ...    

        PropertyGridField('numberOfStandardDeviationsToTruncatedGaussaian', double(3), ...
        'Type', PropertyType('denserealdouble', 'scalar', [2 100]), ...
        'Category', 'Projection', ...
        'DisplayName', 'Number of kept standard deviations', ...
        'Description', 'Gaussian denisty function that represent each dipole is truncated (set to zero) after this many standard deviations. For example, setting this variable to 3 means that the dipole will not have any density after 3 standard deviations.') ...    
        
        PropertyGridField('normalizeInBrainDipoleDenisty', true, ...        
        'Category', 'Projection', ...
        'DisplayName', 'Normalize In-brain Dipole Density', ...
        'Description', 'Scale each dipole density distribution so total density inside brain is equal to one. This prevent reducing the effect of dipole that are located near brain surface.') ...    
        
        
        PropertyGridField('numberOfPermutations', uint32(2000), ...
        'Type', PropertyType('uint32', 'scalar', [300 10e6]), ...    
        'Category', 'Projection', ...
        'DisplayName', 'Number of permutations', ...
        'Description', 'Number of bootstrap permutations for calculation of convergence significance. Miminum p value that can be attained is equal to 1/(number of permutations).') ...

        PropertyGridField('headGridSpacing', double(8), ...
        'Type', PropertyType('denserealdouble', 'scalar', [5 25]), ...
        'Category', 'Projection', ...
        'DisplayName', 'Head-Grid Spacing', ...
        'Description', 'Spacing (in mm) between regular 3D head-grid locations to which measures are projected.') ...                        
    ];
        
end;


f = figure( ...
    'MenuBar', 'none', ...
    'Name', 'Measure Projection Options', ...
    'NumberTitle', 'off', ...
    'Toolbar', 'none', 'visible', fastif(populateWithDefaultAndNoGUI, 'off', 'on'));

% procedural usage
optionsPropertyGrid = PropertyGrid(f, ...            % add property pane to figure
    'Properties', properties);

% if this function has not been invokes as a callback and the 'option' field is missing, fill
% this field with default options without showing a GUI
if populateWithDefaultAndNoGUI
    close(f);
else
    % wait for figure to close
    uiwait(f);
end;



guiOptionValue = optionsPropertyGrid.GetPropertyValues();

STUDY.measureProjection.option = guiOptionValue;

% save it for the next time that the editor is invoked.
STUDY.measureProjection.option.properties = optionsPropertyGrid.Properties;

% put study back in the base workspace
assignin('base', 'STUDY', STUDY);